/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_glimpse_webguide_android_activity_MainActivity */

#ifndef _Included_top_glimpse_webguide_android_activity_MainActivity
#define _Included_top_glimpse_webguide_android_activity_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_glimpse_webguide_android_activity_MainActivity
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 //唉，钱要得有点少。
 */
JNIEXPORT jstring JNICALL Java_top_glimpse_webguide_1android_activity_MainActivity_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
